services:
  - type: web
    name: ethiopian-airlines-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: PUBLIC_VIEW_PASSWORD
        value: ethiopian2024
